### ISSUE TITLE
Trigger some easter egg when I correct NO

### ISSUE THREAD

**Issue by rugk** [ghuntley/noyaml#7]
When I correct NO from:
```yaml 
NI: Nicaragua
NL: Netherlands
NO: Norway # 💣!
```

to

```yaml 
NI: Nicaragua
NL: Netherlands
"NO": Norway # 💣!
```

(after reading that paragraph)

…please trigger some fun thing. Like ghost/magic writing "Yes, exactly like that."
…or a popup "smart ass"…
…or  "You really _needed_ to try that now, did not you?"
